//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.32559
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WortschatzLeipzigAPI.WortschatzWebAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestParameter", Namespace="urn:Thesaurus")]
    [System.SerializableAttribute()]
    public partial class RequestParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string corpusField;
        
        private WortschatzLeipzigAPI.WortschatzWebAPI.DataMatrix parametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string corpus {
            get {
                return this.corpusField;
            }
            set {
                if ((object.ReferenceEquals(this.corpusField, value) != true)) {
                    this.corpusField = value;
                    this.RaisePropertyChanged("corpus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.DataMatrix parameters {
            get {
                return this.parametersField;
            }
            set {
                if ((object.ReferenceEquals(this.parametersField, value) != true)) {
                    this.parametersField = value;
                    this.RaisePropertyChanged("parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DataMatrix", Namespace="urn:Thesaurus", ItemName="dataVectors")]
    [System.SerializableAttribute()]
    public class DataMatrix : System.Collections.Generic.List<WortschatzLeipzigAPI.WortschatzWebAPI.DataVector> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DataVector", Namespace="http://datatypes.webservice.wortschatz.uni_leipzig.de", ItemName="dataRow")]
    [System.SerializableAttribute()]
    public class DataVector : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseParameter", Namespace="urn:Thesaurus")]
    [System.SerializableAttribute()]
    public partial class ResponseParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string executionTimeField;
        
        private WortschatzLeipzigAPI.WortschatzWebAPI.DataMatrix resultField;
        
        private int serviceMagnitudeField;
        
        private int userAmountField;
        
        private int userMaxLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string executionTime {
            get {
                return this.executionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.executionTimeField, value) != true)) {
                    this.executionTimeField = value;
                    this.RaisePropertyChanged("executionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.DataMatrix result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int serviceMagnitude {
            get {
                return this.serviceMagnitudeField;
            }
            set {
                if ((this.serviceMagnitudeField.Equals(value) != true)) {
                    this.serviceMagnitudeField = value;
                    this.RaisePropertyChanged("serviceMagnitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userAmount {
            get {
                return this.userAmountField;
            }
            set {
                if ((this.userAmountField.Equals(value) != true)) {
                    this.userAmountField = value;
                    this.RaisePropertyChanged("userAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userMaxLimit {
            get {
                return this.userMaxLimitField;
            }
            set {
                if ((this.userMaxLimitField.Equals(value) != true)) {
                    this.userMaxLimitField = value;
                    this.RaisePropertyChanged("userMaxLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Thesaurus", ConfigurationName="WortschatzWebAPI.Thesaurus")]
    public interface Thesaurus {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname objRequestParameters aus Namespace urn:Thesaurus nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse execute(WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse> executeAsync(WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname pingReturn aus Namespace urn:Thesaurus nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse ping(WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse> pingAsync(WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="execute", Namespace="urn:Thesaurus", Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.executeRequestBody Body;
        
        public executeRequest() {
        }
        
        public executeRequest(WortschatzLeipzigAPI.WortschatzWebAPI.executeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:Thesaurus")]
    public partial class executeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.RequestParameter objRequestParameters;
        
        public executeRequestBody() {
        }
        
        public executeRequestBody(WortschatzLeipzigAPI.WortschatzWebAPI.RequestParameter objRequestParameters) {
            this.objRequestParameters = objRequestParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="executeResponse", Namespace="urn:Thesaurus", Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.executeResponseBody Body;
        
        public executeResponse() {
        }
        
        public executeResponse(WortschatzLeipzigAPI.WortschatzWebAPI.executeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:Thesaurus")]
    public partial class executeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.ResponseParameter executeReturn;
        
        public executeResponseBody() {
        }
        
        public executeResponseBody(WortschatzLeipzigAPI.WortschatzWebAPI.ResponseParameter executeReturn) {
            this.executeReturn = executeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ping", Namespace="urn:Thesaurus", Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.pingRequestBody Body;
        
        public pingRequest() {
        }
        
        public pingRequest(WortschatzLeipzigAPI.WortschatzWebAPI.pingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pingRequestBody {
        
        public pingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pingResponse", Namespace="urn:Thesaurus", Order=0)]
        public WortschatzLeipzigAPI.WortschatzWebAPI.pingResponseBody Body;
        
        public pingResponse() {
        }
        
        public pingResponse(WortschatzLeipzigAPI.WortschatzWebAPI.pingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:Thesaurus")]
    public partial class pingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pingReturn;
        
        public pingResponseBody() {
        }
        
        public pingResponseBody(string pingReturn) {
            this.pingReturn = pingReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThesaurusChannel : WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThesaurusClient : System.ServiceModel.ClientBase<WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus>, WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus {
        
        public ThesaurusClient() {
        }
        
        public ThesaurusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThesaurusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThesaurusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThesaurusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus.execute(WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public WortschatzLeipzigAPI.WortschatzWebAPI.ResponseParameter execute(WortschatzLeipzigAPI.WortschatzWebAPI.RequestParameter objRequestParameters) {
            WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest inValue = new WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest();
            inValue.Body = new WortschatzLeipzigAPI.WortschatzWebAPI.executeRequestBody();
            inValue.Body.objRequestParameters = objRequestParameters;
            WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse retVal = ((WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus)(this)).execute(inValue);
            return retVal.Body.executeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse> WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus.executeAsync(WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest request) {
            return base.Channel.executeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.executeResponse> executeAsync(WortschatzLeipzigAPI.WortschatzWebAPI.RequestParameter objRequestParameters) {
            WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest inValue = new WortschatzLeipzigAPI.WortschatzWebAPI.executeRequest();
            inValue.Body = new WortschatzLeipzigAPI.WortschatzWebAPI.executeRequestBody();
            inValue.Body.objRequestParameters = objRequestParameters;
            return ((WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus)(this)).executeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus.ping(WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest request) {
            return base.Channel.ping(request);
        }
        
        public string ping() {
            WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest inValue = new WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest();
            inValue.Body = new WortschatzLeipzigAPI.WortschatzWebAPI.pingRequestBody();
            WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse retVal = ((WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus)(this)).ping(inValue);
            return retVal.Body.pingReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse> WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus.pingAsync(WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest request) {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WortschatzLeipzigAPI.WortschatzWebAPI.pingResponse> pingAsync() {
            WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest inValue = new WortschatzLeipzigAPI.WortschatzWebAPI.pingRequest();
            inValue.Body = new WortschatzLeipzigAPI.WortschatzWebAPI.pingRequestBody();
            return ((WortschatzLeipzigAPI.WortschatzWebAPI.Thesaurus)(this)).pingAsync(inValue);
        }
    }
}
